use super::*;

pub fn build_outbounds(
    configs: &[OutboundConfig],
    telemetry: Option<Arc<Telemetry>>,
) -> anyhow::Result<OutboundMap> {
    let mut outbounds: OutboundMap = HashMap::new();
    for config in configs {
        if matches!(config, OutboundConfig::Group { .. }) {
            continue;
        }
        let outbound = build_leaf_outbound(config)?;
        insert_leaf(&mut outbounds, config.name(), outbound)?;
    }

    attach_groups(configs, &mut outbounds, telemetry)?;
    Ok(outbounds)
}

fn build_leaf_outbound(config: &OutboundConfig) -> anyhow::Result<Arc<dyn Outbound>> {
    let outbound: Arc<dyn Outbound> = match config {
        OutboundConfig::Direct { name } => Arc::new(DirectOutbound::new(name.clone())),
        OutboundConfig::Reject { name } => Arc::new(RejectOutbound::new(name.clone())),
        OutboundConfig::Http {
            name,
            server,
            port,
            username,
            password,
        } => Arc::new(HttpOutbound::new(
            name.clone(),
            server.clone(),
            *port,
            username.clone(),
            password.clone(),
        )),
        OutboundConfig::Socks5 {
            name,
            server,
            port,
            username,
            password,
        } => Arc::new(Socks5Outbound::new(
            name.clone(),
            server.clone(),
            *port,
            username.clone(),
            password.clone(),
        )),
        OutboundConfig::Shadowsocks {
            name,
            server,
            port,
            method,
            password,
            plugin,
        } => Arc::new(ShadowsocksOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            method: method.clone(),
            password: password.clone(),
            plugin: plugin.clone(),
            udp_sessions: TokioMutex::new(ShadowsocksUdpPool::default()),
        }),
        OutboundConfig::Trojan {
            name,
            server,
            port,
            password,
            sni,
            skip_cert_verify,
            network,
            ws_path,
            ws_host,
            grpc_service_name,
            transport_headers,
            alpn,
        } => Arc::new(TrojanOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            password: password.clone(),
            sni: sni.clone(),
            skip_cert_verify: *skip_cert_verify,
            network: network.clone(),
            ws_path: ws_path.clone(),
            ws_host: ws_host.clone(),
            grpc_service_name: grpc_service_name.clone(),
            transport_headers: transport_headers.clone(),
            alpn: alpn.clone(),
            udp_sessions: TokioMutex::new(TrojanUdpPool::default()),
        }),
        OutboundConfig::Vmess {
            name,
            server,
            port,
            uuid,
            cipher,
            tls,
            sni,
            skip_cert_verify,
            network,
            ws_path,
            ws_host,
            grpc_service_name,
        } => Arc::new(VmessOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            uuid: uuid.clone(),
            cipher: cipher.clone(),
            tls: *tls,
            sni: sni.clone(),
            skip_cert_verify: *skip_cert_verify,
            network: network.clone(),
            ws_path: ws_path.clone(),
            ws_host: ws_host.clone(),
            grpc_service_name: grpc_service_name.clone(),
            udp_sessions: TokioMutex::new(VmessUdpPool::default()),
        }),
        OutboundConfig::Vless {
            name,
            server,
            port,
            uuid,
            flow,
            security,
            tls,
            sni,
            skip_cert_verify,
            network,
            ws_path,
            ws_host,
            grpc_service_name,
            reality_public_key,
            reality_short_id,
            reality_fingerprint,
            reality_spider_x,
        } => Arc::new(VlessOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            uuid: uuid.clone(),
            flow: flow.clone(),
            security: security.clone(),
            tls: *tls,
            sni: sni.clone(),
            skip_cert_verify: *skip_cert_verify,
            network: network.clone(),
            ws_path: ws_path.clone(),
            ws_host: ws_host.clone(),
            grpc_service_name: grpc_service_name.clone(),
            reality_public_key: reality_public_key.clone(),
            reality_short_id: reality_short_id.clone(),
            reality_fingerprint: reality_fingerprint.clone(),
            reality_spider_x: reality_spider_x.clone(),
            udp_sessions: TokioMutex::new(VlessUdpPool::default()),
        }),
        OutboundConfig::Hysteria2 {
            name,
            server,
            port,
            password,
            sni,
            skip_cert_verify,
            obfs,
            obfs_password,
            alpn,
        } => Arc::new(Hysteria2Outbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            password: password.clone(),
            sni: sni.clone(),
            skip_cert_verify: *skip_cert_verify,
            obfs: obfs.clone(),
            obfs_password: obfs_password.clone(),
            alpn: alpn.clone(),
            udp_sessions: TokioMutex::new(Hysteria2UdpPool::default()),
        }),
        OutboundConfig::Tuic {
            name,
            server,
            port,
            uuid,
            password,
            sni,
            skip_cert_verify,
            congestion_control,
            udp_relay_mode,
            alpn,
        } => Arc::new(TuicOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            uuid: uuid.clone(),
            password: password.clone(),
            sni: sni.clone(),
            skip_cert_verify: *skip_cert_verify,
            congestion_control: congestion_control.clone(),
            udp_relay_mode: udp_relay_mode.clone(),
            alpn: alpn.clone(),
            udp_sessions: TokioMutex::new(TuicUdpPool::default()),
        }),
        OutboundConfig::Naive {
            name,
            server,
            port,
            username,
            password,
            sni,
            skip_cert_verify,
            alpn,
        } => Arc::new(NaiveOutbound::new(
            name.clone(),
            server.clone(),
            *port,
            username.clone(),
            password.clone(),
            sni.clone(),
            *skip_cert_verify,
            alpn.clone(),
        )),
        OutboundConfig::Ssr {
            name,
            server,
            port,
            method,
            password,
            protocol,
            obfs,
            protocol_param,
            obfs_param,
        } => Arc::new(SsrOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            method: method.clone(),
            password: password.clone(),
            protocol: protocol.clone(),
            obfs: obfs.clone(),
            protocol_param: protocol_param.clone(),
            obfs_param: obfs_param.clone(),
        }),
        OutboundConfig::Snell {
            name,
            server,
            port,
            psk,
            method,
            version,
            obfs,
            obfs_host,
            reuse,
        } => Arc::new(SnellOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            psk: psk.clone(),
            method: method.clone(),
            version: *version,
            obfs: obfs.clone(),
            obfs_host: obfs_host.clone(),
            reuse: *reuse,
            v4_pool: Arc::new(TokioMutex::new(SnellV4ConnectionPool::default())),
        }),
        OutboundConfig::Hysteria { name, .. } => Arc::new(UnsupportedProtocolOutbound::new(
            name.clone(),
            "hysteria".to_string(),
        )),
        OutboundConfig::AnyTls {
            name,
            server,
            port,
            password,
            sni,
            skip_cert_verify,
            alpn,
        } => Arc::new(AnyTlsOutbound::new(
            name.clone(),
            server.clone(),
            *port,
            password.clone(),
            sni.clone(),
            *skip_cert_verify,
            alpn.clone(),
        )),
        OutboundConfig::ShadowTls {
            name,
            server,
            port,
            password,
            version,
            sni,
            skip_cert_verify,
        } => Arc::new(ShadowTlsOutbound::new(
            name.clone(),
            server.clone(),
            *port,
            password.clone(),
            *version,
            sni.clone(),
            *skip_cert_verify,
        )),
        OutboundConfig::WireGuard {
            name,
            server,
            port,
            private_key,
            public_key,
            preshared_key,
            ip,
            ipv6,
            allowed_ips,
            reserved,
            mtu,
        } => Arc::new(WireGuardOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            private_key: private_key.clone(),
            public_key: public_key.clone(),
            preshared_key: preshared_key.clone(),
            ip: ip.clone(),
            ipv6: ipv6.clone(),
            allowed_ips: allowed_ips.clone(),
            reserved: reserved.clone(),
            mtu: mtu.unwrap_or(1420),
        }),
        OutboundConfig::Ssh {
            name,
            server,
            port,
            username,
            password,
            private_key,
            private_key_passphrase,
        } => Arc::new(SshOutbound {
            name: name.clone(),
            server: server.clone(),
            port: *port,
            username: username.clone(),
            password: password.clone(),
            private_key: private_key.clone(),
            private_key_passphrase: private_key_passphrase.clone(),
        }),
        OutboundConfig::Mieru { name, .. } => Arc::new(UnsupportedProtocolOutbound::new(
            name.clone(),
            "mieru".to_string(),
        )),
        OutboundConfig::Juicity { name, .. } => Arc::new(UnsupportedProtocolOutbound::new(
            name.clone(),
            "juicity".to_string(),
        )),
        OutboundConfig::Masque { name, .. } => Arc::new(UnsupportedProtocolOutbound::new(
            name.clone(),
            "masque".to_string(),
        )),
        OutboundConfig::OpenVpn { name, .. } => Arc::new(UnsupportedProtocolOutbound::new(
            name.clone(),
            "openvpn".to_string(),
        )),
        OutboundConfig::Unknown { name, protocol, .. } => Arc::new(
            UnsupportedProtocolOutbound::new(name.clone(), protocol.clone()),
        ),
        OutboundConfig::Group { name, .. } => {
            return Err(anyhow!("group {name} must be built after leaf outbounds"));
        }
    };
    Ok(outbound)
}
