[package]
name = "supercore"
version = "0.1.0"
edition = "2021"
description = "Supercore, a Rust-native proxy core for Yueqiu Elevator"
license = "Proprietary"

[dependencies]
anyhow = "1"
async-trait = "0.1"
aes = "0.8"
aes-gcm = "0.10"
axum = "0.7"
base64 = "0.22"
blake2 = "0.10"
blake3 = "1"
boringtun = "0.7"
bytes = "1"
chacha20poly1305 = { version = "0.10", features = ["reduced-round"] }
chacha20 = "0.9"
ccm = "0.5"
lea = "0.5.4"
aegis = { version = "0.9.15", default-features = false, features = ["std", "pure-rust"] }
deoxys = { version = "0.2.0-rc.3", default-features = false, features = ["alloc"] }
zears = "0.2.1"
ascon-aead = "=0.4.2"
poly1305 = "0.8.0"
subtle = "2.5"
cipher = "0.4"
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
crc32c = "0.6"
digest = "0.10"
getrandom = "0.3"
futures = "0.3"
h2 = "0.4"
h3 = "0.0.8"
h3-quinn = "0.0.10"
hkdf = "0.12"
http = "1"
ipnet = { version = "2", features = ["serde"] }
libc = "0.2"
maxminddb = "0.28.1"
md-5 = "0.10"
quinn = "0.11.9"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2", "charset", "blocking"] }
rustls = "0.23"
rustls-pki-types = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
smux = "0.2"
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
shadowsocks = { version = "1.24.0", default-features = false, features = ["aead-cipher", "aead-cipher-extra", "aead-cipher-2022", "aead-cipher-2022-extra", "stream-cipher"] }
socket2 = { version = "0.6", features = ["all"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["compat", "rt"] }
tokio-rustls = "0.26"
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tproxy-config = "7.0.7"
tun2proxy = "0.8.1"
url = "2"
uuid = { version = "1", features = ["v4", "serde"] }
webpki-roots = "1"
x25519-dalek = { version = "3.0.0-rc.0", features = ["getrandom", "static_secrets"] }
yamux = "0.14"
russh = "0.61.2"
cfb-mode = "0.8.2"
argon2 = "0.5.3"
rc4 = "0.1"

[dev-dependencies]
rcgen = "0.13"
tower = { version = "0.5", features = ["util"] }

[build-dependencies]
cc = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[patch.crates-io]
rustls = { path = "vendor/rustls-0.23.40" }
