import Foundation

final class ConfigManager: @unchecked Sendable {
    private let paths: AppPaths

    init(paths: AppPaths, keychain _: KeychainStore) {
        self.paths = paths
    }

    func saveOriginalYAML(_ yaml: String) throws {
        try saveOriginalYAML(yaml, profileID: "default")
    }

    func saveOriginalYAML(_ yaml: String, profileID: String) throws {
        guard looksLikeSubscriptionYAML(yaml) else { throw AppError.invalidYAML }
        try paths.prepareProfileDirectory(id: profileID)
        try yaml.write(to: paths.originalProfile(id: profileID), atomically: true, encoding: .utf8)
    }

    func regenerateSupercoreRuntime(
        profileID: String,
        tunEnabled: Bool,
        runtimeOptions: RuntimeOptions = RuntimeOptions(),
        probeURL: String = "http://www.gstatic.com/generate_204"
    ) throws {
        let originalURL = paths.originalProfile(id: profileID)
        let runtimeURL = paths.supercoreRuntimeProfile(id: profileID)
        guard FileManager.default.fileExists(atPath: originalURL.path) else {
            throw AppError.missingSubscription
        }
        let original = try String(contentsOf: originalURL, encoding: .utf8)
        guard looksLikeSubscriptionYAML(original) else { throw AppError.invalidYAML }
        let runtime = makeSupercoreRuntimeYAML(
            profileID: profileID,
            tunEnabled: tunEnabled,
            runtimeOptions: runtimeOptions,
            customRules: loadCustomRules(profileID: profileID),
            proxyOutboundName: defaultProxyPolicyName(from: original),
            probeURL: probeURL
        )
        try paths.prepareProfileDirectory(id: profileID)
        let temp = runtimeURL.appendingPathExtension("tmp")
        try runtime.write(to: temp, atomically: true, encoding: .utf8)
        if FileManager.default.fileExists(atPath: runtimeURL.path) {
            try FileManager.default.removeItem(at: runtimeURL)
        }
        try FileManager.default.moveItem(at: temp, to: runtimeURL)
    }

    func makeSupercoreRuntimeYAML(
        profileID: String,
        tunEnabled: Bool,
        runtimeOptions: RuntimeOptions = RuntimeOptions(),
        customRules: [CustomRule] = [],
        proxyOutboundName: String = "direct",
        probeURL: String = "http://www.gstatic.com/generate_204"
    ) -> String {
        let ruleLines = customRules.compactMap {
            formatSupercoreRule($0, proxyOutboundName: proxyOutboundName)
        }
        let rulesSection = ruleLines.isEmpty
            ? "rules: []"
            : "rules:\n\(ruleLines.joined(separator: "\n"))"
        let hijackDNS = tunEnabled && runtimeOptions.dnsStrategy != .direct

        return """
        # Generated by 玥球电梯 for Supercore. Do not edit manually.

        core:
          mixed_listen: 127.0.0.1:\(runtimeOptions.mixedPort)
          control_listen: 127.0.0.1:\(runtimeOptions.controllerPort)
          default_outbound: direct
          connect_timeout_ms: 5000
          probe_url: \(probeURL)
          probe_timeout_ms: \(DelayPolicy.timeoutMilliseconds)
          probe_concurrency: \(DelayPolicy.manualConcurrency)
          probe_interval_secs: 300

        tun:
          enabled: \(tunEnabled ? "true" : "false")
          setup: \(tunEnabled ? "true" : "false")
          mtu: 1500
          dns_strategy: \(runtimeOptions.dnsStrategy.rawValue)
          dns_addr: \(runtimeOptions.dnsServer)
          ipv6: false
          tcp_timeout_secs: 600
          udp_timeout_secs: 10
          max_sessions: 200
          bypass:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 127.0.0.0/8
            - 169.254.0.0/16
            - 224.0.0.0/4
            - 255.255.255.255/32
            - fc00::/7
            - fe80::/10
            - ff00::/8
          route_exclude_address:
            - 17.0.0.0/8

        dns:
          enabled: \(hijackDNS ? "true" : "false")
          server: \(runtimeOptions.dnsServer):53
          hijack_udp_53: \(hijackDNS ? "true" : "false")
          timeout_ms: 2000
          block_non_dns_udp: false

        smart_rules:
          enabled: true
          auto_probe: true
          auto_apply_recommendations: false
          direct_outbound: direct
          proxy_outbound:
          direct_probe_timeout_ms: \(DelayPolicy.timeoutMilliseconds)
          probe_cooldown_secs: 300
          min_samples: 2
          state_path: \(quoteYAML(paths.supercoreSmartState(id: profileID).path))
          persist_interval_secs: 30
          max_observations: 10000
          rules: []

        subscriptions:
          use_active: true
          store_path: \(quoteYAML(paths.supercoreSubscriptionStore.path))
          use_first_node_as_default: true
          update_on_start: false
          auto_update: false
          update_interval_secs: 21600
          update_timeout_secs: 10
          update_retries: 1
          update_concurrency: 4

        outbounds:
          - type: direct
            name: direct
          - type: reject
            name: reject

        \(rulesSection)
        """
    }

    func loadCustomRules(profileID: String) -> [CustomRule] {
        guard let data = try? Data(contentsOf: paths.customRules(id: profileID)) else {
            return []
        }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return (try? decoder.decode([CustomRule].self, from: data)) ?? []
    }

    func saveCustomRules(_ rules: [CustomRule], profileID: String) throws {
        try paths.prepareProfileDirectory(id: profileID)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(rules).write(to: paths.customRules(id: profileID), options: .atomic)
    }

    func loadProxyGroups(profileID: String, selectedNodes: [String: String] = [:]) throws -> [ProxyGroup] {
        let originalURL = paths.originalProfile(id: profileID)
        guard FileManager.default.fileExists(atPath: originalURL.path) else {
            return []
        }
        let original = try String(contentsOf: originalURL, encoding: .utf8)
        return parseProxyGroups(from: original, selectedNodes: selectedNodes)
    }

    func parseProxyGroups(from yaml: String, selectedNodes: [String: String] = [:]) -> [ProxyGroup] {
        let lines = yaml.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        var groups: [ProxyGroup] = []
        var inProxyGroups = false
        var currentName: String?
        var currentType = "select"
        var currentNodes: [String] = []
        var currentIncludeAll = false
        var currentFilter: String?
        var currentUseProviders: [String] = []
        var readingProxies = false
        var proxiesIndent = 0

        func finishCurrent() {
            guard let currentName, !currentName.isEmpty else { return }
            let uniqueNodes = currentNodes.reduce(into: [String]()) { result, node in
                if !node.isEmpty && !result.contains(node) {
                    result.append(node)
                }
            }
            let now = selectedNodes[currentName] ?? uniqueNodes.first
            groups.append(
                ProxyGroup(
                    name: currentName,
                    type: currentType,
                    now: now,
                    all: uniqueNodes,
                    includeAll: currentIncludeAll,
                    filter: currentFilter,
                    useProviders: currentUseProviders
                )
            )
        }

        for rawLine in lines {
            let withoutComment = stripComment(rawLine)
            let trimmed = withoutComment.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { continue }
            let indent = leadingWhitespaceCount(withoutComment)

            if indent == 0 {
                if trimmed == "proxy-groups:" {
                    inProxyGroups = true
                    continue
                }
                if inProxyGroups {
                    finishCurrent()
                    currentName = nil
                    break
                }
            }
            guard inProxyGroups else { continue }

            if trimmed.hasPrefix("- ") && indent <= 2 {
                finishCurrent()
                currentName = nil
                currentType = "select"
                currentNodes = []
                currentIncludeAll = false
                currentFilter = nil
                currentUseProviders = []
                readingProxies = false

                let item = String(trimmed.dropFirst(2)).trimmingCharacters(in: .whitespaces)
                if item.hasPrefix("{") {
                    let fields = parseInlineMap(item)
                    currentName = fields["name"]
                    currentType = fields["type"] ?? currentType
                    currentNodes = parseInlineList(fields["proxies"] ?? "")
                    currentIncludeAll = parseBool(fields["include-all"] ?? "")
                    currentFilter = fields["filter"].map(cleanScalar)
                    currentUseProviders = parseInlineList(fields["use"] ?? "")
                } else if item.hasPrefix("name:") {
                    currentName = cleanScalar(String(item.dropFirst("name:".count)))
                }
                continue
            }

            if let value = value(after: "name:", in: trimmed) {
                currentName = value
                continue
            }
            if let value = value(after: "type:", in: trimmed) {
                currentType = value
                continue
            }
            if let value = value(after: "include-all:", in: trimmed) {
                currentIncludeAll = parseBool(value)
                continue
            }
            if let value = value(after: "filter:", in: trimmed) {
                currentFilter = value
                continue
            }
            if let value = value(after: "proxies:", in: trimmed) {
                readingProxies = true
                proxiesIndent = indent
                if value.hasPrefix("[") {
                    currentNodes.append(contentsOf: parseInlineList(value))
                    readingProxies = false
                }
                continue
            }
            if let value = value(after: "use:", in: trimmed) {
                readingProxies = true
                proxiesIndent = indent
                if value.hasPrefix("[") {
                    currentUseProviders.append(contentsOf: parseInlineList(value))
                    readingProxies = false
                }
                continue
            }
            if readingProxies, indent > proxiesIndent, trimmed.hasPrefix("[") {
                currentNodes.append(contentsOf: parseInlineList(trimmed))
                readingProxies = false
                continue
            }
            if readingProxies, indent > proxiesIndent, trimmed.hasPrefix("- ") {
                currentNodes.append(cleanScalar(String(trimmed.dropFirst(2))))
            } else if indent <= proxiesIndent {
                readingProxies = false
            }
        }

        if inProxyGroups {
            finishCurrent()
        }
        return groups
    }

    private func looksLikeSubscriptionYAML(_ yaml: String) -> Bool {
        let lower = yaml.lowercased()
        return lower.contains("proxies:") || lower.contains("proxy-providers:") || lower.contains("proxy-groups:")
    }

    private func formatSupercoreRule(_ rule: CustomRule, proxyOutboundName: String) -> String? {
        guard rule.enabled else { return nil }
        let value = rule.value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty,
              !value.contains("\n") else {
            return nil
        }
        return """
          - target: \(supercoreRuleTarget(rule.target))
            value: \(quoteYAML(value))
            outbound: \(quoteYAML(supercoreOutboundName(for: rule, proxyOutboundName: proxyOutboundName)))
        """
    }

    private func supercoreRuleTarget(_ target: CustomRuleTarget) -> String {
        switch target {
        case .domain: "domain"
        case .domainSuffix: "domain-suffix"
        case .domainKeyword: "domain-keyword"
        case .domainRegex: "domain-regex"
        case .ipCIDR, .ipCIDR6: "ip-cidr"
        case .appName: "app-name"
        case .appPath: "app-path"
        case .appPathRegex: "app-path-regex"
        case .appBundle: "app-bundle"
        }
    }

    private func supercoreOutboundName(for rule: CustomRule, proxyOutboundName: String) -> String {
        switch rule.action {
        case .proxy:
            return proxyOutboundName
        case .direct:
            return "direct"
        case .reject:
            return "reject"
        case .outbound:
            let outbound = rule.outboundName?.trimmingCharacters(in: .whitespacesAndNewlines)
            if let outbound, !outbound.isEmpty {
                return outbound
            }
            return proxyOutboundName
        }
    }

    private func quoteYAML(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private func defaultProxyPolicyName(from yaml: String) -> String {
        let groups = parseProxyGroups(from: yaml)
        if let nodeSelection = groups.first(where: { $0.name.contains("节点选择") }) {
            return nodeSelection.name
        }
        if let proxy = groups.first(where: { $0.name.localizedCaseInsensitiveContains("proxy") }) {
            return proxy.name
        }
        if let proxy = groups.first(where: { $0.name.contains("代理") }) {
            return proxy.name
        }
        return groups.first?.name ?? "Proxy"
    }

    private func leadingWhitespaceCount(_ line: String) -> Int {
        line.prefix { $0 == " " || $0 == "\t" }.count
    }

    private func stripComment(_ line: String) -> String {
        var inSingleQuote = false
        var inDoubleQuote = false
        for (index, char) in line.enumerated() {
            if char == "'", !inDoubleQuote { inSingleQuote.toggle() }
            if char == "\"", !inSingleQuote { inDoubleQuote.toggle() }
            if char == "#", !inSingleQuote, !inDoubleQuote {
                let stringIndex = line.index(line.startIndex, offsetBy: index)
                return String(line[..<stringIndex])
            }
        }
        return line
    }

    private func value(after prefix: String, in line: String) -> String? {
        guard line.hasPrefix(prefix) else { return nil }
        return cleanScalar(String(line.dropFirst(prefix.count)))
    }

    private func cleanScalar(_ value: String) -> String {
        var result = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if result.hasPrefix("\""), result.hasSuffix("\""), result.count >= 2 {
            result.removeFirst()
            result.removeLast()
        } else if result.hasPrefix("'"), result.hasSuffix("'"), result.count >= 2 {
            result.removeFirst()
            result.removeLast()
        }
        return result
    }

    private func parseInlineList(_ value: String) -> [String] {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix("[") else { return [] }
        return trimmed
            .trimmingCharacters(in: CharacterSet(charactersIn: "[]"))
            .split(separator: ",")
            .map { cleanScalar(String($0)) }
            .filter { !$0.isEmpty }
    }

    private func parseInlineMap(_ value: String) -> [String: String] {
        let body = value.trimmingCharacters(in: CharacterSet(charactersIn: "{} "))
        var result: [String: String] = [:]
        var key = ""
        var buffer = ""
        var inValue = false
        var bracketDepth = 0
        for char in body {
            if char == ":", !inValue {
                key = buffer.trimmingCharacters(in: .whitespacesAndNewlines)
                buffer = ""
                inValue = true
            } else if char == "[", inValue {
                bracketDepth += 1
                buffer.append(char)
            } else if char == "]", inValue {
                bracketDepth -= 1
                buffer.append(char)
            } else if char == ",", inValue, bracketDepth == 0 {
                result[cleanScalar(key)] = cleanScalar(buffer)
                key = ""
                buffer = ""
                inValue = false
            } else {
                buffer.append(char)
            }
        }
        if inValue {
            result[cleanScalar(key)] = cleanScalar(buffer)
        }
        return result
    }

    private func parseBool(_ value: String) -> Bool {
        let normalized = cleanScalar(value).lowercased()
        return normalized == "true" || normalized == "yes" || normalized == "1"
    }
}
